version: '3'
services:
  dynamodb:
    image: 'amazon/dynamodb-local'
    ports:
      - '8000:8000'
  mongo:
    image: 'mongo'
    ports:
      - '27017:27017'
  redis:
    image: 'redis'
    ports:
      - '6379:6379'
